version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5115:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
